server:
  port: 8088
  servlet:
    context-path: '/ead-payment/'

spring:
  application:
    name: ead-payment-service
  datasource:
    url:  jdbc:postgresql://localhost:5432/ead-payment
    username: postgres
    password: ronaldo
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  output:
    ansi:
      enabled: Always
  rabbitmq:
    host: localhost #com essa configuração minha aplicação consegui se conectar com rabbit localmente
    port: 5672
    username: rabbitmq
    password: rabbitmq

logging:
  level:
    com.ead: INFO
    root: INFO
    org.springframework.web: INFO
    org.hibernate: INFO

# Exchange, Queue
ead:
  broker:
    exchange:
      userEventExchange: ead.userevent
      paymentCommandExchange: ead.paymentCommand
    queue:
      userEventQueue:
        name: ead.userevent.ms.payment
      paymentCommandQueue:
        name: ead.paymentcommand.ms.payment
    key:
      paymentCommandKey: ms.payment
  stripe:
    secretKey: '{cipher}f44538f443a2aba2af693c52b72967b205bb099f3f7f233227a71c736f1eb97649ee12b75df41ffcdf924347f7aebd978f79464e5dde4561e37598190b5e4452e6d317de1782414c79628bb16771fc20a4ff88d2ea2508ae4fd804632931d3d6c692197adf9fdb5fce87a17c8d807265f56ea3f3d8fbbc55a6c70f808eb42bbd'        

#Actuator
management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health