server:
  port: 8088
  servlet:
    context-path: '/ead-payment/'

spring:
  application:
    name: ead-payment-service
  datasource:
    url:  jdbc:postgresql://localhost:5432/ead-payment
    username: postgres
    password: ronaldo
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  output:
    ansi:
      enabled: Always
  rabbitmq:
    host: localhost #com essa configuração minha aplicação consegui se conectar com rabbit localmente
    port: 5672
    username: rabbitmq
    password: rabbitmq

logging:
  level:
    com.ead: INFO
    root: INFO
    org.springframework.web: INFO
    org.hibernate: INFO

# Exchange, Queue
ead:
  broker:
    exchange:
      userEventExchange: ead.userevent
    queue:
      userEventQueue:
        name: ead.userevent.ms.payment

#Actuator
management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health
